export const state={
  appConfig:null,
  config:null,
  taskId:'',
  map:null,
  popup:null,
  rawFeatures:[],
  pending:[],
  accepted:[],
  inconsistencies:[],
  mode:'pending',
  selectedKey:null,
  addKeys:new Set(),
  removeKeys:new Set(),
  inconsistencyResolutions:new Map(),
  savedSignature:'',
  postpassTimestamp:null,
  baseHash:'',
  importedProposals:[],
  conflictResolutions:new Map(),
  search:'',
  type:'all',
  mapReady:false
};
